#version 440 core

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;


layout(std430, binding = 0) buffer storageBuffer
{
    vec2 positions[10000];
};

uniform vec2 pixie;

float random (vec2 st)
{
    return fract(sin(dot(st.xy, vec2(12.9898,78.233)))*43758.5453123);
}

void main()
{

    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

	positions[x + y * 10].x = pixie.x;
	positions[x + y * 10].y = pixie.y;
}